# Generated by Django 5.1.1 on 2025-03-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Myapp.property')),
            ],
        ),
    ]
