# Generated by Django 5.1.1 on 2025-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforwardListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('price', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agent_name', models.CharField(blank=True, max_length=255)),
                ('agent_phones', models.JSONField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scraped_MakaziListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_image_url', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
