# Generated by Django 5.1.1 on 2025-05-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_beforwardlisting_scraped_makazilisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scraped_MakaziListing',
            new_name='Scrape_MakaziListing',
        ),
    ]
