# Generated by Django 5.1.1 on 2025-01-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_profile_profile_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_completed',
        ),
    ]
