# Generated by Django 5.1.1 on 2025-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_help_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('national', 'National'), ('religious', 'Religious')], max_length=20)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
            ],
        ),
    ]
