# Generated by Django 5.1.1 on 2025-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_propertylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylocation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
