# Generated by Django 5.1.1 on 2025-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_propertylocation_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es salaam', 'Dar es salaam'), ('Dooma', 'Dodoma'), ('Ruvuma', 'Ruvuma'), ('Tabora', 'Tabora'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Lindi', 'Lindi'), ('Kigoma', 'Kigoma'), ('Katavi', 'Katavi'), ('Geita', 'Geita'), ('Manyara', 'Manyara'), ('Kilimanjaro', 'Kilimanjaro'), ('Mara', 'Mara'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Songwe', 'Songwe'), ('Tanga', 'Tanga'), ('Shinyanga', 'Shinyanga'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Pemba Kaskazini', 'Pemba Kaskazini'), ('Pemba Kusini', 'Pemba Kusini'), ('Pwani', 'Pwani'), ('Rukwa', 'Rukwa'), ('Singida', 'Singida'), ('Simiyu', 'Simiyu'), ('Zanzibar Kaskazini', 'Zanzibar Kaskazini'), ('Zanzibar Kusini', 'Zanzibar Kusini'), ('Zanzibar Mjini Magharibi', 'Zanzibar Mjini Magharibi')], max_length=30),
        ),
    ]
