# Generated by Django 5.1.1 on 2025-05-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_rename_scraped_makazilisting_scrape_makazilisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeforwardListing',
            new_name='Scrape_BeforwardListing',
        ),
    ]
