# Generated by Django 5.1.6 on 2025-08-17 18:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_agent_image_of_agent_1_offer_offer_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_owner',
        ),
        migrations.AddField(
            model_name='client',
            name='client_image_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
