# Generated by Django 5.1.1 on 2025-01-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_profile_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_completed',
        ),
    ]
