# Generated by Django 5.1.6 on 2025-08-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_remove_property_image_remove_property_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='image_of_agent',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_image',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_image',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='image_of_partners',
        ),
        migrations.RemoveField(
            model_name='popularplace',
            name='image_of_place',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
